version: '3'
services:
  blog_server:
    build:
      context: ..
      dockerfile: docker/server.dockerfile
    volumes:
      - ${PWD}/../volumes/log:/log
      - ${PWD}/../volumes/tmp:/tmp
    ports:
      - "8888:8888"
    container_name: "blog_server"
    depends_on:
      - blog_db
  
  blog_testing:
    build:
      context: ..
      dockerfile: docker/testing.dockerfile
    container_name: "blog_testing"

  blog_db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "127.0.0.1:3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    container_name: "blog_db"

  db_restore:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_HOST=${DB_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ../db:/db
      - ../shell:/shell
    depends_on:
      - blog_db
    links:
      - blog_db
    command: "./shell/deploy.sh restore"
    container_name: "db_restore"

volumes:
  mysql_data: